# Default values for mainflux.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cassandra:
  enabled: false

influxdb:
  enabled: true

mongodb:
  enabled: false
