---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{ .Values.natsCluster.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "crd-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: nats.io
  names:
    kind: NatsCluster
    listKind: NatsClusterList
    plural: natsclusters
    singular: natscluster
    shortNames:
    - nats
  scope: Namespaced
  version: v1alpha2
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{ .Values.natsServiceRole.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "crd-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: nats.io
  names:
    kind: NatsServiceRole
    listKind: NatsServiceRoleList
    plural: natsserviceroles
    singular: natsservicerole
  scope: Namespaced
  version: v1alpha2
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.natsOperator.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.natsOperator.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.natsOperator.name }}
    spec:
      serviceAccountName: {{ .Values.natsOperator.name }}
      containers:
      - name: {{ .Values.natsOperator.name }}
        image: {{ .Values.natsOperatorImage }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        ports:
        - name: readyz
          containerPort: {{ .Values.natsOperator.ports.readyz }}
        env: 
        {{- range $key, $fieldPath := .Values.envFieldPath }}
        - name: {{ $key }}
          valueFrom:
            fieldRef:
              fieldPath: {{ $fieldPath | quote }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.natsOperator.ports.readyz }}
          initialDelaySeconds: {{ .Values.probe.initialDelay }}
          timeoutSeconds: {{ .Values.probe.timeout }}
