apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.dashflux.name }}
  labels:
    component: {{ .Values.dashflux.name }}
spec:
  selector:
    component: {{ .Values.dashflux.name }}
  ports:
  - port: {{ .Values.dashflux.port }}
  type: {{ .Values.global.serviceType }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.dashflux.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    component: {{ .Values.dashflux.name }}
spec:
  replicas: {{ .Values.global.replicas }}
  template:
    metadata:
      labels:
        component: {{ .Values.dashflux.name }}
    spec:
      containers:
      - name: {{ .Values.dashfluxImage }}
        image: {{ .Values.dashfluxImage }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        ports:
        - containerPort: {{ .Values.dashflux.port }}
