apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.influxdb.diskName }}-{{ .Release.Namespace }}
  namespace: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.volumes.influxdb.diskName }}
spec:
  capacity:
    storage: {{ .Values.volumes.size }}
  accessModes:
    - {{ .Values.volumes.accessMode }}
  hostPath:
    path: {{ .Values.volumes.influxdb.path }}-{{ .Release.Namespace }}
  persistentVolumeReclaimPolicy: Delete
