apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.influxdb.diskName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.volumes.influxdb.diskName }}
spec:
  capacity:
    storage: {{ .Values.volumes.size }}
  accessModes:
    - {{ .Values.volumes.accessMode }}
  hostPath:
    path: {{ .Values.volumes.influxdb.path }}
  persistentVolumeReclaimPolicy: Recycle
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ .Values.volumes.influxdb.claimName }}
spec:
  accessModes:
    - {{ .Values.volumes.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volumes.size }}
---
apiVersion: v1
kind: Pod
metadata:
  namespace: {{ .Values.global.namespace }}
  name: 
  labels:
    name: {{ .Values.influxdb.name }}
spec:
  containers:
    - name: {{ .Values.influxdb.name }}
      image: {{ .Values.influxdbImage }}
        env:
        {{- range $key, $value := .Values.influxdb.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
      ports:
        - containerPort: {{ .Values.influxdb.port }}
      volumeMounts:
        - mountPath: {{ .Values.volumes.influxdb.mountPath }}
          name: {{ .Values.volumes.influxdb.name }}
  volumes:
    - name: {{ .Values.volumes.influxdb.name }}
      persistentVolumeClaim:
        claimName: {{ .Values.volumes.influxdb.claimName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.influxdb.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.influxdb.name }}
spec:
  ports:
    - port: {{ .Values.influxdb.port }}
  selector:
    name: {{ .Values.influxdb.name }}
