# Default values for mainflux adapters
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

coap:
  enabled: true

http:
  enabled: true

mqtt:
  enabled: true

ws:
  enabled: true

